<template>
  <div class="app-container">
    <el-row>
      <el-button type="primary" @click="getContent">编辑器内容</el-button>
    </el-row>
    <tinymce-editor ref="editor" style="padding: 20px 0" v-model="content" :height="500"></tinymce-editor>
  </div>
</template>

<script>
import TinymceEditor from "@/components/tinymce";

export default {
  components: {
    TinymceEditor,
  },
  data() {
    return {
      content: `<p class="MsoNormal" style="text-autospace: ideograph-numeric; mso-pagination: none; text-align: center; line-height: 30.0000pt; mso-line-height-rule: exactly;" align="center"><strong><span style="font-family: 宋体; font-size: 26pt;"><span style="font-family: 宋体;">证</span></span></strong><strong><span style="font-family: 宋体; font-size: 26pt;">&nbsp;&nbsp;&nbsp;</span></strong><strong><span style="font-family: 宋体; font-size: 26pt;"><span style="font-family: 宋体;">明</span></span></strong></p>
<p class="MsoNormal" style="text-autospace: ideograph-numeric; mso-pagination: none; line-height: 30.0000pt; mso-line-height-rule: exactly;"><span style="mso-spacerun: 'yes'; font-family: 仿宋_GB2312; font-size: 16.0000pt; mso-font-kerning: 1.0000pt;"><span style="font-family: 仿宋_GB2312;">xxx小区客服中心</span></span><span style="mso-spacerun: 'yes'; font-family: 仿宋_GB2312; font-size: 16.0000pt; mso-font-kerning: 1.0000pt;"><span style="font-family: 仿宋_GB2312;">：</span></span></p>
<p class="MsoNormal" style="text-indent: 32.0000pt; mso-char-indent-count: 2.0000; text-autospace: ideograph-numeric; mso-pagination: none; line-height: 30.0000pt; mso-line-height-rule: exactly;"><span style="mso-spacerun: 'yes'; font-family: 仿宋_GB2312; font-size: 16.0000pt; mso-font-kerning: 1.0000pt;"><span style="font-family: 仿宋_GB2312;">贵</span></span><span style="mso-spacerun: 'yes'; font-family: 仿宋_GB2312; font-size: 16.0000pt; mso-font-kerning: 1.0000pt;"><span style="font-family: 仿宋_GB2312;">小区</span></span><u><span style="font-family: 仿宋_GB2312; font-size: 16pt;">&nbsp; &nbsp; &nbsp; &nbsp; </span></u><span style="mso-spacerun: 'yes'; font-family: 仿宋_GB2312; font-size: 16.0000pt; mso-font-kerning: 1.0000pt;"><span style="font-family: 仿宋_GB2312;">号楼</span></span><u><span style="font-family: 仿宋_GB2312; font-size: 16pt;">&nbsp; &nbsp; &nbsp; &nbsp;</span></u><span style="mso-spacerun: 'yes'; font-family: 仿宋_GB2312; font-size: 16.0000pt; mso-font-kerning: 1.0000pt;"><span style="font-family: 仿宋_GB2312;">单元</span></span><u><span style="font-family: 仿宋_GB2312; font-size: 16pt;">&nbsp; &nbsp; &nbsp; </span></u><span style="mso-spacerun: 'yes'; font-family: 仿宋_GB2312; font-size: 16.0000pt; mso-font-kerning: 1.0000pt;"><span style="font-family: 仿宋_GB2312;">号业主</span></span><u><span style="font-family: 仿宋_GB2312; font-size: 16pt;">&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp; &nbsp;</span></u><span style="mso-spacerun: 'yes'; font-family: 仿宋_GB2312; font-size: 16.0000pt; mso-font-kerning: 1.0000pt;"><span style="font-family: 仿宋_GB2312;">，身份证号</span></span><u><span style="font-family: 仿宋_GB2312; font-size: 16pt;">&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;</span></u><span style="mso-spacerun: 'yes'; font-family: 仿宋_GB2312; font-size: 16.0000pt; mso-font-kerning: 1.0000pt;">,系我单位职工，因工作性质特殊，需正常工作，经常出入贵小区，我单位会在疫情期间加强管控，保证做到疫情期间对员工进行每天两次测体温，并做好防护，望准许。</span></p>
<p class="MsoNormal" style="text-indent: 32pt; line-height: 30pt;"><span style="mso-spacerun: 'yes'; font-family: 仿宋_GB2312; font-size: 16.0000pt; mso-font-kerning: 1.0000pt;"><span style="font-family: 仿宋_GB2312;">特此证明</span></span><span style="mso-spacerun: 'yes'; font-family: 仿宋_GB2312; font-size: 16.0000pt; mso-font-kerning: 1.0000pt;"><span style="font-family: 仿宋_GB2312;">。</span></span></p>
<p class="MsoNormal" style="text-indent: 32.0000pt; mso-char-indent-count: 2.0000; text-autospace: ideograph-numeric; mso-pagination: none; text-align: right; line-height: 30.0000pt; mso-line-height-rule: exactly;" align="right"><span style="mso-spacerun: 'yes'; font-family: 仿宋_GB2312; font-size: 16.0000pt; mso-font-kerning: 1.0000pt;"><span style="font-family: 仿宋_GB2312;">单位名称：（公章）</span></span></p>
<p class="MsoNormal" style="text-autospace: ideograph-numeric; mso-pagination: none; text-align: right; line-height: 30.0000pt; mso-line-height-rule: exactly;" align="right"><span style="mso-spacerun: 'yes'; font-family: 仿宋_GB2312; font-size: 16.0000pt; mso-font-kerning: 1.0000pt;"><span style="font-family: 仿宋_GB2312;">年</span></span><span style="mso-spacerun: 'yes'; font-family: 仿宋_GB2312; font-size: 16.0000pt; mso-font-kerning: 1.0000pt;">&nbsp;&nbsp;</span><span style="mso-spacerun: 'yes'; font-family: 仿宋_GB2312; font-size: 16.0000pt; mso-font-kerning: 1.0000pt;">&nbsp;&nbsp;月 &nbsp;</span><span style="mso-spacerun: 'yes'; font-family: 仿宋_GB2312; font-size: 16.0000pt; mso-font-kerning: 1.0000pt;">&nbsp;&nbsp;</span><span style="mso-spacerun: 'yes'; font-family: 仿宋_GB2312; font-size: 16.0000pt; mso-font-kerning: 1.0000pt;">&nbsp;日</span></p>
<p class="MsoNormal" style="text-autospace: ideograph-numeric; mso-pagination: none; text-align: right; line-height: 30.0000pt; mso-line-height-rule: exactly;" align="right">&nbsp;</p>
<hr />
<p class="MsoNormal" style="text-autospace: ideograph-numeric; mso-pagination: none; text-align: center; line-height: 30.0000pt; mso-line-height-rule: exactly;" align="center"><strong><span style="font-family: 宋体; font-size: 26pt;">&nbsp;</span></strong></p>
<p class="MsoNormal" style="text-autospace: ideograph-numeric; mso-pagination: none; text-align: center; line-height: 30.0000pt; mso-line-height-rule: exactly;" align="center"><strong><span style="font-family: 宋体; font-size: 26pt;"><span style="font-family: 宋体;">证</span></span></strong><strong><span style="font-family: 宋体; font-size: 26pt;">&nbsp;&nbsp;&nbsp;</span></strong><strong><span style="font-family: 宋体; font-size: 26pt;"><span style="font-family: 宋体;">明</span></span></strong></p>
<p class="MsoNormal" style="text-autospace: ideograph-numeric; mso-pagination: none; line-height: 30.0000pt; mso-line-height-rule: exactly;"><span style="mso-spacerun: 'yes'; font-family: 仿宋_GB2312; font-size: 16.0000pt; mso-font-kerning: 1.0000pt;"><span style="font-family: 仿宋_GB2312;">xxx小区客服中心</span></span><span style="mso-spacerun: 'yes'; font-family: 仿宋_GB2312; font-size: 16.0000pt; mso-font-kerning: 1.0000pt;"><span style="font-family: 仿宋_GB2312;">：</span></span></p>
<p class="MsoNormal" style="text-indent: 32.0000pt; mso-char-indent-count: 2.0000; text-autospace: ideograph-numeric; mso-pagination: none; line-height: 30.0000pt; mso-line-height-rule: exactly;"><span style="mso-spacerun: 'yes'; font-family: 仿宋_GB2312; font-size: 16.0000pt; mso-font-kerning: 1.0000pt;"><span style="font-family: 仿宋_GB2312;">贵</span></span><span style="mso-spacerun: 'yes'; font-family: 仿宋_GB2312; font-size: 16.0000pt; mso-font-kerning: 1.0000pt;"><span style="font-family: 仿宋_GB2312;">小区</span></span><u><span style="font-family: 仿宋_GB2312; font-size: 16pt;">&nbsp; &nbsp; &nbsp; &nbsp; </span></u><span style="mso-spacerun: 'yes'; font-family: 仿宋_GB2312; font-size: 16.0000pt; mso-font-kerning: 1.0000pt;"><span style="font-family: 仿宋_GB2312;">号楼</span></span><u><span style="font-family: 仿宋_GB2312; font-size: 16pt;">&nbsp; &nbsp; &nbsp; &nbsp; </span></u><span style="mso-spacerun: 'yes'; font-family: 仿宋_GB2312; font-size: 16.0000pt; mso-font-kerning: 1.0000pt;"><span style="font-family: 仿宋_GB2312;">单元</span></span><u><span style="font-family: 仿宋_GB2312; font-size: 16pt;">&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;</span></u><span style="mso-spacerun: 'yes'; font-family: 仿宋_GB2312; font-size: 16.0000pt; mso-font-kerning: 1.0000pt;"><span style="font-family: 仿宋_GB2312;">号业主</span></span><u><span style="font-family: 仿宋_GB2312; font-size: 16pt;">&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp;&nbsp;</span></u><span style="mso-spacerun: 'yes'; font-family: 仿宋_GB2312; font-size: 16.0000pt; mso-font-kerning: 1.0000pt;"><span style="font-family: 仿宋_GB2312;">，身份证号</span></span><u><span style="font-family: 仿宋_GB2312; font-size: 16pt;">&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </span></u><span style="mso-spacerun: 'yes'; font-family: 仿宋_GB2312; font-size: 16.0000pt; mso-font-kerning: 1.0000pt;">,系我单位职工，因工作性质特殊，需正常工作，经常出入贵小区，我单位会在疫情期间加强管控，保证做到疫情期间对员工进行每天两次测体温，并做好防护，望准许。</span></p>
<p class="MsoNormal" style="text-indent: 32pt; line-height: 30pt;"><span style="mso-spacerun: 'yes'; font-family: 仿宋_GB2312; font-size: 16.0000pt; mso-font-kerning: 1.0000pt;"><span style="font-family: 仿宋_GB2312;">特此证明</span></span></p>
<p class="MsoNormal" style="text-indent: 32.0000pt; mso-char-indent-count: 2.0000; text-autospace: ideograph-numeric; mso-pagination: none; text-align: right; line-height: 30.0000pt; mso-line-height-rule: exactly;" align="right"><span style="mso-spacerun: 'yes'; font-family: 仿宋_GB2312; font-size: 16.0000pt; mso-font-kerning: 1.0000pt;"><span style="font-family: 仿宋_GB2312;">单位名称：（公章）</span></span></p>
<p class="MsoNormal" style="text-autospace: ideograph-numeric; mso-pagination: none; text-align: right; line-height: 30.0000pt; mso-line-height-rule: exactly;" align="right"><span style="mso-spacerun: 'yes'; font-family: 仿宋_GB2312; font-size: 16.0000pt; mso-font-kerning: 1.0000pt;"><span style="font-family: 仿宋_GB2312;">年</span></span><span style="mso-spacerun: 'yes'; font-family: 仿宋_GB2312; font-size: 16.0000pt; mso-font-kerning: 1.0000pt;">&nbsp;&nbsp;</span><span style="mso-spacerun: 'yes'; font-family: 仿宋_GB2312; font-size: 16.0000pt; mso-font-kerning: 1.0000pt;">&nbsp;&nbsp;月 &nbsp;</span><span style="mso-spacerun: 'yes'; font-family: 仿宋_GB2312; font-size: 16.0000pt; mso-font-kerning: 1.0000pt;">&nbsp;&nbsp;</span><span style="mso-spacerun: 'yes'; font-family: 仿宋_GB2312; font-size: 16.0000pt; mso-font-kerning: 1.0000pt;">&nbsp;日</span></p>
<p class="MsoNormal" style="text-autospace: ideograph-numeric; mso-pagination: none; text-align: center; line-height: 30.0000pt; mso-line-height-rule: exactly;" align="center">&nbsp;</p>`,
    };
  },
  methods: {
    // 获得内容
    getContent() {
      let value = this.$refs.editor.value;
      const fast = value.indexOf("<body>");
      const last = value.lastIndexOf("</body>");
      if (fast != -1 && last != -1) {
        value = value.substring(fast + 7, last);
      }
      this.content = value;
      this.$baseMessage("请在浏览器Console中查看", "success");
      console.log(this.content);
    },
  },
};
</script>
